version: '3.8'

services:
  testing:
    container_name: hello-world-api-testing
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run test && npm run test:e2e && npm run test:coverage