name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:cov

      - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
